-- Script generated by SimpleSpy - credits to exx#9394
local args = {
    [1] = "SendMoney",
    [2] = game:GetService("Players").JayToCapHot6,
    [3] = 1
}

game:GetService("ReplicatedStorage").Phone:FireServer(unpack(args))
local args = {
    [1] = "SendPrivateMessage",
    [2] = "ds",
    [3] = game:GetService("Players").JayToCapHot6
}
game:GetService("ReplicatedStorage").Phone:FireServer(unpack(args))
local args = {
    [1] = "Buy",
    [2] = "Sedan"
}
game:GetService("ReplicatedStorage").CarHandler:FireServer(unpack(args))




-----------------------------------------------------------------------

----------------------------------------------------------------
-- Functions
-- Functions
-- START FINITY GUI
-- START FINITY GUI
-- START FINITY GUI
-- START FINITY GUI
-- START FINITY GUI
-- START FINITY GUI
-- START FINITY GUI
-- START FINITY GUI
-- START FINITY GUI
-- START FINITY GUI
local Finity = loadstring(game:HttpGet("https://raw.githubusercontent.com/LocalSmail/Finity/main/Library"))()
Finity:EnableHubMode(true) -- doesn't fill log
print("")
local FinityWindow = Finity.new("Street Life Gamer GUI for Quality of Life", true, false, "", false, "Home to close | Inputs are Case Sensitive")

local Category1 = FinityWindow:Category("Exploits + Shop")
local Category2 = FinityWindow:Category("ATM + Money + TP")
local VenPayTribune = FinityWindow:Category("VenPay Tribune")

local ExploitsSector = Category1:Sector("Exploits")
local ShopSector = Category1:Sector("Shop")
local ATMSector = Category2:Sector("ATM")
local MoneySector = Category2:Sector("Money")
local SafeSector = Category2:Sector("Safe")
local TPSector = Category2:Sector("Teleports")
local VenPaySector = VenPayTribune:Sector("I love you venpay exploit")

--Local Variables
local gun = "ARPistol"
local person = ""
local AutoWithdraw = false
local TraderEnabled = false
local ItemToStore = ""
local ItemToTake = ""
local AimbotEnabled = false

-- Roblox Variables
local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer
local Camera = workspace.CurrentCamera
local RunService = game:GetService("RunService")
local UIS = game:GetService("UserInputService")
local TweenService = game:GetService("TweenService")
local ReplicatedStorage =  game:GetService("ReplicatedStorage")

local FOVCircle = Drawing.new("Circle")
FOVCircle.Position = Vector2.new(Camera.ViewportSize.X / 2, Camera.ViewportSize.Y / 2)
FOVCircle.Radius = 80
FOVCircle.Color = Color3.fromRGB(255,255,255)
FOVCircle.NumSides = 64

-- Quality of Life proximity prompts
for i,v in game:GetDescendants() do
    if v and v:IsA("ProximityPrompt") then
        v.HoldDuration = 0
    end
end
-- and max zoom
LocalPlayer.CameraMaxZoomDistance = 1000


-- FUNCTIONS
local DepositMoney = function(amount) 
    local args = {
        [1] = "Deposit",
        [2] = amount
    }
    ReplicatedStorage.ATM:FireServer(unpack(args))
end
local WithdrawMoney = function(amount) 
    local args = {
        [1] = "Withdraw",
        [2] = amount
    }
    ReplicatedStorage.ATM:FireServer(unpack(args))
end
local Respawn = function () 
    local args = {
        [1] = "ss"
    }

    game:GetService("Lighting").bt:FireServer(unpack(args))
end
local Teleport = function(x,y,z)
    LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(x,y,z)
end

local FindPlayerToAimbot = function() 
    local Mouse = LocalPlayer:GetMouse()
	


    local MaxDistance = 80
	local closestDistance = math.huge
	local player = nil
	
	for i, v in pairs(Players:GetPlayers()) do
        local HumanoidRootPart = v.Character:FindFirstChild("HumanoidRootPart")
		local Humanoid = v.Character:FindFirstChild("Humanoid")
        
        if not HumanoidRootPart or v == LocalPlayer or v.Character == nil or Humanoid.Health == 0 then
			continue
		elseif (LocalPlayer.Character.HumanoidRootPart.CFrame.Y - v.Character.HumanoidRootPart.CFrame.Y) > 10 then
            continue -- Too Far Underneath or above
        end
        
        local ScreenPoint = Camera:WorldToScreenPoint(HumanoidRootPart.Position)
        local VectorDistance =  (Vector2.new(UIS:GetMouseLocation().X, UIS:GetMouseLocation().Y) - Vector2.new(ScreenPoint.X,ScreenPoint.Y)).Magnitude
        
        if ScreenPoint.Z < 0 then continue end -- They are behind us
        if VectorDistance < closestDistance and VectorDistance < MaxDistance then
            closestDistance = VectorDistance
            player = v
        end
        
	end
    
	return player
end

local LookAtHeadOfPlayer = function(player)
    if player == nil then return end
    Target = player.Character
    LocalPlayer.CameraMaxZoomDistance = 0.5
    for i,v in pairs(Players:GetPlayers()) do
        if Target and Target:FindFirstChild("Head") then
            Camera.CFrame = CFrame.new(Camera.CFrame.p, Target.Head.CFrame.p)
        end
    end

    game.Players.LocalPlayer.CameraMaxZoomDistance = 1000
end


-- TRADING FUNCTIONS
-- Constants for floor, ceiling, and profit margins
local FLOOR_PRICE = 1000
local CEILING_PRICE = 10000
local MIN_PROFIT_MARGIN = 0.05 -- 5%
local MAX_PROFIT_MARGIN = 0.15 -- 15%

-- Function to calculate volatility based on price fluctuations
local function calculateVolatility(previousPrice, currentPrice)
    return math.abs(currentPrice - previousPrice) / previousPrice
end

-- Modified determineAction function
local function determineAction(currentPrice, lastPurchasePrice, previousPrice)
    local volatility = calculateVolatility(previousPrice, currentPrice)
    local profitMargin = (currentPrice - lastPurchasePrice) / lastPurchasePrice

    -- Determine action based on profit margin and volatility
    if profitMargin < MIN_PROFIT_MARGIN or volatility > MAX_PROFIT_MARGIN then
        return "Purchase", currentPrice, profitMargin
    elseif profitMargin > MAX_PROFIT_MARGIN then
        return "Sell", currentPrice, profitMargin
    else
        return "Hold", currentPrice, profitMargin
    end
end

-- Function to get the current price (placeholder, to be implemented)
local function getCurrentPrice()
    -- Placeholder implementation
    return ReplicatedStorage.Crypto.Value
end

-- Function to get the current number of shares (placeholder)
local function getCurrentShares()
    return LocalPlayer.Crypto.Value 
end

-- Function to get the remaining time (placeholder, to be implemented)
local function getTimeRemaining()
    local countdownText = LocalPlayer.PlayerGui.PhoneUI.Main.CryptoFrame.Countdown.Text
    local timeString = countdownText:gsub("s", "") -- Remove the "s" character
    local timeRemaining = tonumber(timeString) -- Convert the string to a number
    return timeRemaining
end

-- Main trading function with the new logic
local function tradeCrypto()
    local lastPurchasePrice = getCurrentPrice() -- Initialize the last purchase price with the current price
    local previousPrice = getCurrentPrice() -- Initialize with the current price
    local currentShares = getCurrentShares() -- Get the current number of shares

    -- Ensure the user starts with 10 shares
    while currentShares < 10 do
        local args = {
            [1] = "Crypto", 
            [2] = "Purchase", 
            [3] = previousPrice -- Assuming each buy action is for 1 share
        }

        --game:GetService("ReplicatedStorage").Phone:FireServer(unpack(args)) -- Testing without so it doesnt lose moenyt
        currentShares = currentShares + 1
        wait(0.5) -- Wait for a half second before the next buy action (adjust as needed)
    end

    -- Continue with the existing trading logic
    while TraderEnabled do
        -- Check if the remaining time is 29 seconds
        if getTimeRemaining() == 29 then
            local currentPrice = getCurrentPrice()
            local action, price, profitMarginPercent = determineAction(currentPrice, lastPurchasePrice, previousPrice)

            if action == "Purchase" and currentShares < 10 then
                lastPurchasePrice = price -- Update the last purchase price
                currentShares = currentShares + 1 -- Update the number of shares
            elseif action == "Sell" and currentShares > 0 then
                currentShares = currentShares - 1 -- Update the number of shares
            end

            if action ~= "Hold" then
                local args = {
                    [1] = "Crypto", 
                    [2] = action, 
                    [3] = price
                }

               ReplicatedStorage.Phone:FireServer(unpack(args))
            end

            previousPrice = currentPrice -- Update the previous price for the next iteration
        end

        -- Wait for the next price change
        repeat wait(1) until getTimeRemaining() == 29 or TraderEnabled == false
    end
end









-- START GUI -- -- -- -- -- 


-- SHOP
local AutoWithdrawCheckbox = ShopSector:Cheat("Checkbox", "Auto Withdraw? (recommended)", function (checkbox)
    AutoWithdraw = checkbox
end)

local Label = ShopSector:Cheat("Label", "                   Clips")

local BuyPistolClip = ShopSector:Cheat("Button", "Buy Pistol Clip", function ()
    -- Script generated by SimpleSpy - credits to exx#9394
    if AutoWithdraw == true then WithdrawMoney(50) end
    local args = {
        [1] = "Pistol Clip",
        [2] = 50
    }

    ReplicatedStorage.GBuy:FireServer(unpack(args))

end, {})

local BuyARClip = ShopSector:Cheat("Button", "Buy AR Clip", function ()
    -- Script generated by SimpleSpy - credits to exx#9394
    if AutoWithdraw == true then WithdrawMoney(100) end
    local args = {
        [1] = "AR Clip",
        [2] = 100
    }

    ReplicatedStorage.GBuy:FireServer(unpack(args))

end, {})

local Label = ShopSector:Cheat("Label", "                   Guns (ignores level)")

local Buy1911 = ShopSector:Cheat("Button", "Buy 1911", function ()
    -- Script generated by SimpleSpy - credits to exx#9394
    if AutoWithdraw == true then WithdrawMoney(1000) end
    local args = {
        [1] = "1911",
        [2] = 1000
    }

    ReplicatedStorage.GBuy:FireServer(unpack(args))

end, {})

local BuyARPistol = ShopSector:Cheat("Button", "Buy ARPistol", function ()
    -- Script generated by SimpleSpy - credits to exx#9394
    if AutoWithdraw == true then WithdrawMoney(5000) end
    local args = {
        [1] = "ARPistol",
        [2] = 5000
    }

    ReplicatedStorage.GBuy:FireServer(unpack(args))

end, {})

local BuyGlockSwitch = ShopSector:Cheat("Button", "Buy GlockSwitch", function ()
    -- Script generated by SimpleSpy - credits to exx#9394
    if AutoWithdraw == true then WithdrawMoney(5250) end
    local args = {
        [1] = "GlockSwitch",
        [2] = 5250
    }

    ReplicatedStorage.GBuy:FireServer(unpack(args))

end, {})

local BuyAK = ShopSector:Cheat("Button", "Buy AK-47", function ()
    -- Script generated by SimpleSpy - credits to exx#9394
    if AutoWithdraw == true then WithdrawMoney(8500) end
    local args = {
        [1] = "AK-47",
        [2] = 8500
    }

    ReplicatedStorage.GBuy:FireServer(unpack(args))

end, {})

local Label = ShopSector:Cheat("Label", "                   Other")

local BuyC4 = ShopSector:Cheat("Button", "Buy C4", function ()
    -- Script generated by SimpleSpy - credits to exx#9394
    if AutoWithdraw == true then WithdrawMoney(1500) end
    local args = {
        [1] = "C4",
        [2] = 1500
    }
    ReplicatedStorage.Buy:FireServer(unpack(args))

end, {})

local BuyMentos = ShopSector:Cheat("Button", "Buy Mentos Bag", function ()
    -- Script generated by SimpleSpy - credits to exx#9394
    if AutoWithdraw == true then WithdrawMoney(300) end
    local args = {
        [1] = "MentosBag",
        [2] = 300
    }
    ReplicatedStorage.Buy:FireServer(unpack(args))

end, {})


-- EXPLOITS
local InstantRespawn = ExploitsSector:Cheat("Button", "Instant Respawn", function ()
    DepositMoney(game.Players.LocalPlayer.stored.Money.Value)
    local args = {
        [1] = "ss"
    }

    game:GetService("Lighting").bt:FireServer(unpack(args))
end, {})

local FastInteract = ExploitsSector:Cheat("Button", "Instant Interact", function ()
    for i,v in game:GetDescendants() do
        if v and v:IsA("ProximityPrompt") then
            v.HoldDuration = 0
        end
    end
end)

local FastInteract = ExploitsSector:Cheat("Checkbox", "NoClip Camera", function (checkbox)
    if checkbox == true then
        LocalPlayer.DevCameraOcclusionMode = "Invisicam"
    else
        LocalPlayer.DevCameraOcclusionMode = "Zoom"
    end
end)




local Label = ExploitsSector:Cheat("Label", "Type offical name for gun + Hold gun + Press Button")

local SetGunForKill = ExploitsSector:Cheat("Textbox", "type in gun to use -----", function (newgun)
    gun = newgun
end, {})

local ShootAllWithGun = ExploitsSector:Cheat("Button", "Shoot EVERYBODY With Gun ", function ()
    for i,v in pairs(Players:GetPlayers()) do
        local args = {
            [1] = LocalPlayer.Character:FindFirstChild(gun),
            [2] = LocalPlayer,
            [3] = v.Character.Humanoid,
            [4] = v.Character.HumanoidRootPart,
            [5] = 30,
            [6] = {
                [1] = 0,
                [2] = 0,
                [3] = false,
                [4] = false,
                [5] = LocalPlayer.Character:FindFirstChild(gun).GunScript_Server.IgniteScript,
                [6] = LocalPlayer.Character:FindFirstChild(gun).GunScript_Server.IcifyScript,
                [7] = 100,
                [8] = 100
            },
            [7] = {
                [1] = false,
                [2] = 5,
                [3] = 3
            },
            [8] = v.Character.Head,
            [9] = {
                [1] = false,
                [2] = {
                    [1] = 1930359546
                },
                [3] = 1,
                [4] = 1.5,
                [5] = 1
            },
            [10] = Vector3.new(-433.24053955078125, -323.75885009765625, -158.63999938964844),
            [11] = Vector3.new(-0.956211268901825, 0.00013869439135305583, -0.29267749190330505),
            [12] = true
        }
        ReplicatedStorage.InflictTarget:InvokeServer(unpack(args))
        
    end
end, {})

local SetPersonToKill = ExploitsSector:Cheat("Textbox", "type person to shoot -----", function (newperson)
    person = newperson
end)

local ShootSingleWithGun = ExploitsSector:Cheat("Button", "Shoot Person With Gun", function ()

    local args = {
        [1] = LocalPlayer.Character:FindFirstChild(gun),
        [2] = LocalPlayer,
        [3] = Players:FindFirstChild(person).Character.Humanoid,
        [4] = Players:FindFirstChild(person).Character.HumanoidRootPart,
        [5] = 30,
        [6] = {
            [1] = 0,
            [2] = 0,
            [3] = false,
            [4] = false,
            [5] = LocalPlayer.Character:FindFirstChild(gun).GunScript_Server.IgniteScript,
            [6] = LocalPlayer.Character:FindFirstChild(gun).GunScript_Server.IcifyScript,
            [7] = 100,
            [8] = 100
        },
        [7] = {
            [1] = false,
            [2] = 5,
            [3] = 3
        },
        [8] = Players:FindFirstChild(person).Character.Head,
        [9] = {
            [1] = false,
            [2] = {
                [1] = 1930359546
            },
            [3] = 1,
            [4] = 1.5,
            [5] = 1
        },
        [10] = Vector3.new(-433.24053955078125, -323.75885009765625, -158.63999938964844),
        [11] = Vector3.new(-0.956211268901825, 0.00013869439135305583, -0.29267749190330505),
        [12] = true
    }
    ReplicatedStorage.InflictTarget:InvokeServer(unpack(args))

end, {})


local Label = ExploitsSector:Cheat("Label", "Hold fists and use keybind to fastpunch, is small delay.")

local SuperPunch = ExploitsSector:Cheat("Keybind", "Punch", function ()
    for i,v in pairs(Players:GetPlayers()) do

        local args = {
            [1] = v.Character.Humanoid,
            [2] = 5
        }
        
        LocalPlayer.Character.Fist.LocalScript.punched:InvokeServer(unpack(args))

    end
end, {default = "R"})

local Label = ExploitsSector:Cheat("Label", "")

local Label = ExploitsSector:Cheat("Label", "Injects Infinite Yield, very nice to use click tp")

local SuperPunch = ExploitsSector:Cheat("Button", "Inject IY", function ()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)

local Label = ExploitsSector:Cheat("Label", "Right click to lock on to head")

local Aimbot = ExploitsSector:Cheat("Checkbox", "Aimbot", function (checkbox)
    if checkbox == true then
        local connection, connection2
        connection = UIS.InputBegan:Connect(function(input)
            if input.UserInputType == Enum.UserInputType.MouseButton2 then 
                AimbotEnabled = true
            end
        end)
        connection2 = UIS.InputEnded:Connect(function(input)
            if input.UserInputType == Enum.UserInputType.MouseButton2 then 
                AimbotEnabled = false
            end
        end)
    else
        connection:Disconnect()
        connection2:Disconnect()
    end
end)
RunService.RenderStepped:Connect(function()
    if AimbotEnabled then
        LookAtHeadOfPlayer(FindPlayerToAimbot())
    end
end)


-- ATM
local Label = ATMSector:Cheat("Label", "Press enter to run function")

local Deposit = ATMSector:Cheat("Textbox", "Deposit", function (amount)
    DepositMoney(amount)
end, {})

local Withdraw = ATMSector:Cheat("Textbox", "Withdraw", function (amount)
    WithdrawMoney(amount)
end, {})

local DepositAll = ATMSector:Cheat("Button", "Deposit All to Bank", function ()
    DepositMoney(LocalPlayer.stored.Money.Value)
end, {})


-- MONEY
local Label = MoneySector:Cheat("Label", "FARMING WILL KILL YOUR PLAYER but it does work")

local CarMoneyFarm = MoneySector:Cheat("Button", "Car Money Farm", function (amount)
    DepositMoney(LocalPlayer.stored.Money.Value)
    Respawn()
    wait(2)
    local hd, rlos, en, mad
    local iteration = 0
    local firepp = function(pp,xx, teleport)
        hd = pp.HoldDuration
        rlos = pp.RequiresLineOfSight
        en = pp.Enabled
        mad = pp.MaxActivationDistance

        --

        pp.HoldDuration = 0
        pp.RequiresLineOfSight = false
        --pp.Enabled = true
        pp.MaxActivationDistance = math.huge 
        if en == true then
            if teleport == true then
                LocalPlayer.Character.HumanoidRootPart.CFrame = pp.Parent.Parent.CFrame + Vector3.new(0,2,2)
                iteration = iteration + 1
            end
            wait(0.25)
            fireproximityprompt(pp,xx)  
        end
        --

        --pp.HoldDuration = hd
        pp.RequiresLineOfSight = rlos
        --pp.Enabled = en
        pp.MaxActivationDistance = mad
        if en == true then
            return "enabled"
        end
    end

    for i,v in workspace.Interactions:GetDescendants() do
        if v and v.Name == "ProximityPrompt" and v:IsA("ProximityPrompt") then
            
            local result = ""
            local result = firepp(v,1, true) 
            if result == "enabled" then
                wait(2.5)
                local result = firepp(v,1, false) 
                wait(0.25)
                DepositMoney(LocalPlayer.stored.Money.Value)
                
                if iteration == 3 then 
                    Respawn() -- prevents lagbacks
                    wait(1)
                    iteration = 0
                end
            else
                continue
            end

        end
    end
end)

local CryptoTrader = MoneySector:Cheat("Checkbox", "Crypto Trader", function (checkbox)
    TraderEnabled = checkbox
    if checkbox == true then
        tradeCrypto()
    end

end)


-- SAFE
local ChooseItemToStore = SafeSector:Cheat("Textbox", "Type item to STORE IN SAFE", function (textbox)
    ItemToStore = textbox
end)
local StoreItemToSafe = SafeSector:Cheat("Button", "Store Item", function (dropdown)
    local args = {
    [1] = "Change",
    [2] = ItemToStore,
    [3] = "Backpack",
    [4] = LocalPlayer.Character.HumanoidRootPart
    }
    ReplicatedStorage.Inventory:FireServer(unpack(args))
end)
local ChooseItemToTake = SafeSector:Cheat("Textbox", "Type item to TAKE FROM SAFE", function (textbox)
    ItemToTake = textbox
end)
local TakeItemFromSafe = SafeSector:Cheat("Button", "Take Item", function (dropdown)
    local args = {
    [1] = "Change",
    [2] = ItemToTake,
    [3] = "Inv",
    [4] = LocalPlayer.Character.HumanoidRootPart
    }
    ReplicatedStorage.Inventory:FireServer(unpack(args))
end)


-- TELEPORT
local BankVaultTP = TPSector:Cheat("Button", "TP to Bank Vault", function (amount)
    Teleport(-1239,-260,-371)
end)

local BankLootSellerTP = TPSector:Cheat("Button", "TP to Bank Loot Seller", function (amount)
    Teleport(-856,3,385)
end)

local CarDealerTP = TPSector:Cheat("Button", "TP to Car Dealer", function (amount)
    Teleport(-680,4,54)
end)

-- I love venpay
local Label = VenPaySector:Cheat("Label", "Rip VenPay Exploit")



























































































local hd, rlos, en, mad
local result = ""
local firepp = function(pp,xx)
    hd = pp.HoldDuration
    rlos = pp.RequiresLineOfSight
    en = pp.Enabled
    mad = pp.MaxActivationDistance

    --

    pp.HoldDuration = 0
    pp.RequiresLineOfSight = false
    pp.Enabled = true
    pp.MaxActivationDistance = math.huge 
    if en == true then
        game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = pp.Parent.CFrame + Vector3.new(0,0,0)
    end
    --

    fireproximityprompt(pp,xx)  

    --

    pp.HoldDuration = hd
    pp.RequiresLineOfSight = rlos
    pp.Enabled = en
    pp.MaxActivationDistance = mad
    if en == true then
        return "stop"
    end
end

for i,v in workspace.Plants:GetDescendants() do
    if v and v.Name == "Interact" and v:IsA("ProximityPrompt") then

        local result = firepp(v,1) 
        if result == "stop" then
            break
        end
    end
end























































-- Script generated by SimpleSpy - credits to exx#9394
--[[
local args = {
    [1] = "Buy",
    [2] = "Scooter"
}

game:GetService("ReplicatedStorage").CarHandler:FireServer(unpack(args))
]]